version: 1.0.0.{build}-{branch}

build_script:
  - echo "Dummy loop build" > loop_build.txt
  - timeout 2

artifacts:
   - path: loop_build.txt
     name: loop_build (%appveyor_build_version%)

deploy:
    release: loop_build-v$(appveyor_build_version)
    description: 'loop_build for tag $(appveyor_repo_tag_name) [skip ci]'
    provider: GitHub
    auth_token:
      secure: s0No7srfoBSMGEXAHdcx7q8Z2Q7Bnk/O/3eCq0xsoub4y4UQTRMJWU0PWQHjwGpi # your encrypted token from GitHub
    artifact: loop_build.txt             # Archived bin directory
    draft: false
    prerelease: false
